### ISSUE TITLE
Mumbles for MumbleBox

### ISSUE THREAD

**Issue by EllenFawkes** [EllenFawkes/PurrplingBot#35]
Please put your mumbles here. Type a comment with your concept of mumbles and send it!

### Zařazeno

- **Pes|pejsek|hafan**
Ustup satane
http://images.huffingtonpost.com/2012-06-13-catsdogsfight3-thumb.jpg
https://696f2f1b047a974c9d02-fe376ee1391e139016dd683a89931094.ssl.cf1.rackcdn.com/images/cat-and-dog.jpg
https://s-media-cache-ak0.pinimg.com/236x/85/27/d0/8527d0dbf7dd572651513689320c6354--kittens-and-puppies-cuddling-kittens.jpg
- **lokmon|Loki**
https://media.giphy.com/media/suCJQGchI6oBW/giphy.gif
https://s-media-cache-ak0.pinimg.com/originals/68/e0/b3/68e0b310b35e416ffbb6e1bcfcadf195.gif
- **PurrplingCat|Ellen|CallMeFoxie|Ashley**
To je moje milovaná maminka <3
To je moje panička :-*
Miaw! Miluju jí!
- **kočička**
Já jsem kočička
Mám ráda kočičky
Mňaaaaau!
- **PurrplingBot**
Já?
Kdo zmínil moje jméno?
Neber si mé jméno nadarmo do huby!
- **dinner|večeře|jídlo|oběd|snídaně**
Já chci kapsičku!
Tuňáčka prosím!
Moje miska je prázdná. Co takhle nejdřív nakrmit mě
- **myslet|myslela?**
Hlavně nemyslet! Od toho jsem tady já
- **příkaz.?|přikázat|přikázal.?**
Přikazovat můžu jenom já! Já jsem kočka, já tě vlastním, ty posloucháš, já si dělám, co chci. Mňau!!
Ty mi nemáš co přikazovat!
- **kocour**
Musíš mě strašit s takovým vetřelcem?
*syčí a prská*
Děkuji za tip na rande, ale jsem homosexuálně orientovaná číča :)
- **wtf**
What the fuck??
http://gph.is/2gkSlvA
http://gph.is/1NSZmjg
http://gph.is/2br0sEH
http://gph.is/XIypEz
- **drápat|drápky|drápy|škrábat**
Neříkej dvakrát. Dlouho jsem si o nic nebrousila drápky,tak si dávej pozor, nebo to tvůj gauč schytá! http://gph.is/2cZuQpE
- **nečum|čumí.?**
http://gph.is/28O95EW
- **kafe|káva|životabudič**
http://gph.is/28O95EW
http://gph.is/1syOzSF
- **lol|haha|hehe|hihi|rofl**
Hahaa, to je vtipný!
Heh, to není vtipný!
Bože, to je trapný jak fusekle v sandálích...
Hahahahahaha... Jejda, já si smíchy učůrknula
http://gph.is/190sukp
http://gph.is/166zc3v
http://gph.is/1za9Unn
http://gph.is/YBA7E7
- **Carmilla|Laura**
http://gph.is/2bf7tFA
http://gph.is/2cKuDax
http://gph.is/2d9gX7W
http://gph.is/2d3DFPC
https://giphy.com/gifs/carmilla-oUuNPQzjr5Li/links
- **Minecraft|craftit**
http://gph.is/2fd79O9
Ach, zase ty kostičky

**Comment by CallMeFoxie** [comment]
dinner/večeře:
Já chci kapsičku!
Tuňáčka prosim!
...

**Comment by EllenFawkes** [comment]
----------- odbaveno

**Comment by lokmon1** [comment]
Návrh od Zajdy: 
Pes, pejsek: 
- Ustup satane
-  http://images.huffingtonpost.com/2012-06-13-catsdogsfight3-thumb.jpg
- https://696f2f1b047a974c9d02-fe376ee1391e139016dd683a89931094.ssl.cf1.rackcdn.com/images/cat-and-dog.jpg
- https://s-media-cache-ak0.pinimg.com/236x/85/27/d0/8527d0dbf7dd572651513689320c6354--kittens-and-puppies-cuddling-kittens.jpg
- https://pixabay.com/p-775116/?no_redirect

**Comment by lokmon1** [comment]
lokmon, Loki: 
- https://media.giphy.com/media/suCJQGchI6oBW/giphy.gif
- https://s-media-cache-ak0.pinimg.com/originals/68/e0/b3/68e0b310b35e416ffbb6e1bcfcadf195.gif

**Comment by EllenFawkes** [comment]
Odbaveno

**Comment by EllenFawkes** [comment]
Added new mumbles. To be backported to 1.2.x

**Comment by EllenFawkes** [comment]
Backported to 1.2.x
